# Generated by Django 5.2.7 on 2025-10-21 19:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


# Constantes para evitar duplicación de literales
EMPRESA_MODEL = 'empresas.empresa'
VN_CODIGO = 'Código'
VN_FECHA_CREACION = 'Fecha de Creación'


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno del impuesto', max_length=10, verbose_name=VN_CODIGO)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Impuesto')),
                ('tipo_impuesto', models.CharField(choices=[('IVA', 'IVA (Impuesto al Valor Agregado)'), ('ICA', 'ICA (Impuesto de Industria y Comercio)'), ('RETEFUENTE', 'Retención en la Fuente'), ('RETEIVA', 'Retención de IVA'), ('RETEICA', 'Retención de ICA'), ('OTRO', 'Otro Impuesto')], max_length=15, verbose_name='Tipo de Impuesto')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje del impuesto (ej: 19.00 para IVA del 19%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentaje (%)')),
                ('activo', models.BooleanField(default=True, verbose_name='Impuesto Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name=VN_FECHA_CREACION)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=EMPRESA_MODEL, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'ordering': ['tipo_impuesto', 'nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno del método de pago', max_length=10, verbose_name=VN_CODIGO)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Método de Pago')),
                ('tipo_metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('CONSIGNACION', 'Consignación'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Método')),
                ('requiere_referencia', models.BooleanField(default=False, help_text='Si requiere número de cheque, referencia de transferencia, etc.', verbose_name='Requiere Referencia')),
                ('activo', models.BooleanField(default=True, verbose_name='Método Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name=VN_FECHA_CREACION)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=EMPRESA_MODEL, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno del producto/servicio', max_length=20, verbose_name=VN_CODIGO)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_producto', models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], default='producto', max_length=10, verbose_name='Tipo')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de Venta')),
                ('precio_costo', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de Costo')),
                ('inventariable', models.BooleanField(default=True, help_text='Si el producto maneja control de inventario', verbose_name='Maneja Inventario')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock Mínimo')),
                ('activo', models.BooleanField(default=True, verbose_name='Producto Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name=VN_FECHA_CREACION)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=EMPRESA_MODEL, verbose_name='Empresa')),
                ('impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.impuesto', verbose_name='Impuesto Aplicable')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tercero', models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('ambos', 'Cliente y Proveedor')], max_length=10, verbose_name='Tipo de Tercero')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte'), ('NIT', 'NIT (Número de Identificación Tributaria)')], default='CC', max_length=3, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(help_text='Número de identificación sin puntos ni espacios', max_length=20, validators=[django.core.validators.RegexValidator(message='El número de documento debe contener solo números (6-20 dígitos)', regex='^\\d{6,20}$')], verbose_name='Número de Documento')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social / Nombre Completo')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('direccion', models.TextField(blank=True, max_length=300, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Formato: +5713001234567 o 13001234567', regex='^\\+?57?[0-9]{7,12}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, verbose_name='Tercero Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name=VN_FECHA_CREACION)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=EMPRESA_MODEL, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
                'ordering': ['razon_social'],
                'unique_together': {('empresa', 'numero_documento')},
            },
        ),
    ]

