# Generated by Django 5.2.7 on 2025-11-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_cambiar_stock_a_entero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono o celular', max_length=20, verbose_name='Teléfono'),
        ),
    ]
