# Generated by Django 5.2.7 on 2025-10-17 01:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte'), ('NIT', 'NIT (Número de Identificación Tributaria)')], default='CC', max_length=3, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(help_text='Número de identificación sin puntos ni espacios', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento debe contener solo números (6-20 dígitos)', regex='^\\d{6,20}$')], verbose_name='Número de Documento')),
                ('telefono', models.CharField(help_text='Número de teléfono celular colombiano', max_length=15, validators=[django.core.validators.RegexValidator(message='Formato: +573001234567 o 3001234567', regex='^\\+?57?[0-9]{10,12}$')], verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=1, verbose_name='Género')),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('U', 'Unión Libre'), ('D', 'Divorciado/a'), ('V', 'Viudo/a')], max_length=1, verbose_name='Estado Civil')),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa de residencia', max_length=200, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(default='Cundinamarca', max_length=100, verbose_name='Departamento')),
                ('pais', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('profesion', models.CharField(blank=True, max_length=100, verbose_name='Profesión')),
                ('empresa', models.CharField(blank=True, max_length=100, verbose_name='Empresa')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('acepta_terminos', models.BooleanField(default=False, verbose_name='Acepta Términos y Condiciones')),
                ('acepta_politica_privacidad', models.BooleanField(default=False, verbose_name='Acepta Política de Privacidad')),
                ('recibir_notificaciones', models.BooleanField(default=True, verbose_name='Recibir Notificaciones por Email')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Perfil Activo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
