# Generated by Django 5.2.7 on 2025-11-07 14:52

from django.db import migrations
import time


def fix_empty_numero_documento(apps, schema_editor):
    """Arreglar perfiles con numero_documento vacío asignando números temporales únicos"""
    perfil_usuario_model = apps.get_model('accounts', 'PerfilUsuario')
    
    perfiles_vacios = perfil_usuario_model.objects.filter(numero_documento='')
    
    for i, perfil in enumerate(perfiles_vacios):
        # Generar número temporal único
        numero_temp = f"TEMP{perfil.usuario.id:06d}{int(time.time() % 1000):03d}"
        
        # Asegurar que sea único
        while perfil_usuario_model.objects.filter(numero_documento=numero_temp).exists():
            numero_temp = f"TEMP{perfil.usuario.id:06d}{int(time.time() % 1000 + i):03d}"
        
        perfil.numero_documento = numero_temp
        perfil.save()


def reverse_fix_empty_numero_documento(apps, schema_editor):
    """Reversión no implementada - no es necesaria"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_crear_perfil_usuario_colombiano'),
    ]

    operations = [
        migrations.RunPython(
            fix_empty_numero_documento,
            reverse_fix_empty_numero_documento
        ),
    ]
