"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl
from datetime import timedelta

# Cargar variables de entorno
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# La SECRET_KEY SIEMPRE debe estar en variables de entorno (archivo .env o Render)
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError(
        "❌ SECRET_KEY no está configurada.\n"
        "   📝 Para desarrollo local: Crea un archivo .env con SECRET_KEY=tu-clave\n"
        "   🚀 Para producción (Render): Configura SECRET_KEY en Environment Variables"
    )

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
# https://docs.djangoproject.com/en/3.0/ref/settings/#allowed-hosts
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    ALLOWED_HOSTS.append("*.onrender.com")

# CSRF Trusted Origins para Render
CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "https://finalpoo2.onrender.com",
]
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend(["http://127.0.0.1:8000", "http://localhost:8000"])

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Django REST Framework + JWT
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",  # Para logout seguro
    "corsheaders",  # Para CORS en API
    # Apps del proyecto
    "core.apps.CoreConfig",  # AdminSite personalizado y template tags
    "accounts",
    "api",  # Nueva app para API
    # Apps del sistema contable
    "empresas",  # Gestión de empresas y roles multi-empresa
    "catalogos",  # Terceros, impuestos, métodos de pago, productos
    "facturacion",  # Facturas de venta y detalles
    "tesoreria",  # Pagos, cobros y cuentas bancarias
    "contabilidad",  # Plan de cuentas, asientos y partidas
    "reportes",  # Reportes contables y configuraciones
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # DEBE ir justo después de SecurityMiddleware
    "corsheaders.middleware.CorsMiddleware",  # CORS debe ir temprano
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "core.middleware.DevCSRFMiddleware",  # Middleware personalizado para desarrollo
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Middleware personalizado para sistema multi-empresa
    "empresas.middleware.EmpresaActivaMiddleware",
    # Middleware para historial de cambios
    "empresas.middleware_historial.ThreadLocalMiddleware",
    "empresas.middleware_historial.HistorialCambiosMiddleware",
]
ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración de PostgreSQL con Neon
tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": tmpPostgres.path.replace("/", ""),
        "USER": tmpPostgres.username,
        "PASSWORD": tmpPostgres.password,
        "HOST": tmpPostgres.hostname,
        "PORT": 5432,
        "OPTIONS": dict(parse_qsl(tmpPostgres.query)),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-co"  # Español de Colombia

TIME_ZONE = "America/Bogota"  # Zona horaria de Colombia

USE_I18N = True

USE_TZ = True

# Configuración de localización
LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Configuración de almacenamiento de archivos estáticos (Django 5.2+)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication settings
LOGIN_URL = "accounts:login"
# LOGIN_REDIRECT_URL manejado por CustomLoginView según tipo de usuario
LOGOUT_REDIRECT_URL = "accounts:login"

# Email configuration - Gmail SMTP con clave de aplicación
# IMPORTANTE: Para generar clave de aplicación de Gmail:
# 1. Ir a https://myaccount.google.com/security
# 2. Habilitar verificación en 2 pasos
# 3. Crear clave de aplicación para "S_CONTABLE Django"
# 4. Usar esa clave de 16 caracteres en GOOGLE_APP_PASSWORD
# NUNCA subir la clave de aplicación al repositorio

# ===== CONFIGURACIÓN DE EMAIL =====
# Render Free Tier bloquea conexiones SMTP (puertos 25, 587, 465)
# Usar SendGrid API en producción y SMTP en desarrollo

SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY", "")

if SENDGRID_API_KEY:
    # ✅ PRODUCCIÓN: Usar SendGrid (funciona en Render gratuito)
    EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
    SENDGRID_API_KEY = SENDGRID_API_KEY
    SENDGRID_SANDBOX_MODE_IN_DEBUG = False  # Desactivar sandbox para enviar emails reales
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip()
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER).strip()
    SERVER_EMAIL = DEFAULT_FROM_EMAIL
    
    # SendGrid no necesita estas configuraciones SMTP
    EMAIL_HOST = None
    EMAIL_PORT = None
    EMAIL_USE_SSL = False
    EMAIL_USE_TLS = False
    EMAIL_HOST_PASSWORD = None
    
    print("📧 Email: Usando SendGrid API (producción)")
else:
    # 🏠 DESARROLLO: Usar Gmail SMTP (solo funciona localmente)
    EMAIL_BACKEND = os.getenv(
        "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
    )
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "465"))
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "True").lower() in ('true', '1', 'yes')
    EMAIL_USE_TLS = False
    
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip()
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "").strip()
    DEFAULT_FROM_EMAIL = os.getenv("EMAIL_HOST_USER", "").strip()
    SERVER_EMAIL = DEFAULT_FROM_EMAIL
    
    print("📧 Email: Usando Gmail SMTP (desarrollo local)")

# Timeout para envío de emails
EMAIL_TIMEOUT = 30

# ===== CONFIGURACIÓN DE CONVIVENCIA: SESIONES + JWT =====

# Django REST Framework - SOLO para rutas /api/
# Las vistas MVT (HTML) siguen usando sesiones normalmente
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # JWT SOLO para API (/api/*) - No afecta vistas MVT
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # Sesiones para compatibilidad con browsable API
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",  # Solo en desarrollo
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# Simple JWT Configuration
# Access token: 15 minutos (seguridad)
# Refresh token: 1 día (usabilidad)
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,  # Rota refresh tokens por seguridad
    "BLACKLIST_AFTER_ROTATION": True,  # Invalida tokens antiguos
    "UPDATE_LAST_LOGIN": True,  # Actualiza last_login en cada token
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=15),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# CORS Configuration - Seguro para producción, HTTP solo en desarrollo
if DEBUG:
    # Solo en desarrollo local se permite HTTP
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",  # React/Vue frontend
        "http://127.0.0.1:3000",
        "http://localhost:8080",  # Vue CLI default
        "http://127.0.0.1:8080",
    ]
else:
    # En producción, solo HTTPS
    CORS_ALLOWED_ORIGINS = os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "https://example.com",  # Reemplazar con tu dominio de producción
    ).split(",")

CORS_ALLOW_CREDENTIALS = True  # Para cookies de sesión si es necesario

# CSRF Configuration - Usa HTTPS en producción
if DEBUG:
    # Solo en desarrollo local se permite HTTP
    CSRF_TRUSTED_ORIGINS = [
        "http://127.0.0.1:8000",
        "http://localhost:8000",
        "http://127.0.0.1:57765",  # Browser preview
        "http://localhost:57765",
    ]
    # Configuraciones de CSRF para desarrollo
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_HTTPONLY = False
    CSRF_USE_SESSIONS = False
    CSRF_COOKIE_SAMESITE = "Lax"
else:
    # En producción, solo HTTPS (más seguro)
    CSRF_TRUSTED_ORIGINS = os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "https://example.com",  # Reemplazar con tu dominio de producción
    ).split(",")
    # Configuraciones de seguridad para producción
    CSRF_COOKIE_SECURE = True  # Requiere HTTPS
    CSRF_COOKIE_HTTPONLY = True  # Previene acceso desde JavaScript
    CSRF_COOKIE_SAMESITE = "Strict"  # Protección contra CSRF

# Configuración de sesiones
SESSION_COOKIE_AGE = 3600  # 1 hora
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

# ===== CONFIGURACIÓN DE SEGURIDAD PARA PRODUCCIÓN =====
if not DEBUG:
    # Forzar HTTPS en producción
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Configuración de cookies seguras
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Strict"

    # Cabeceras de seguridad
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"
