"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl
from datetime import timedelta
import dj_database_url

# Cargar variables de entorno
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-key-for-development-only-change-in-production')

# Para desarrollo, usar una clave por defecto si no está configurada
if not os.getenv('SECRET_KEY') and DEBUG:
    print("⚠️  Usando SECRET_KEY por defecto para desarrollo. Configura SECRET_KEY en .env para producción.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Django REST Framework + JWT
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # Para logout seguro
    'corsheaders',  # Para CORS en API
    
    # Apps del proyecto
    'accounts',
    'api',  # Nueva app para API
    
    # Apps del sistema contable
    'empresas',      # Gestión de empresas y roles multi-empresa
    'catalogos',     # Terceros, impuestos, métodos de pago, productos
    'facturacion',   # Facturas de venta y detalles
    'tesoreria',     # Pagos, cobros y cuentas bancarias
    'contabilidad',  # Plan de cuentas, asientos y partidas
    'reportes',      # Reportes contables y configuraciones
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS debe ir temprano
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.DevCSRFMiddleware',  # Middleware personalizado para desarrollo
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Middleware personalizado para sistema multi-empresa
    'empresas.middleware.EmpresaActivaMiddleware',
    
    # Middleware para historial de cambios
    'empresas.middleware_historial.ThreadLocalMiddleware',
    'empresas.middleware_historial.HistorialCambiosMiddleware',
]
ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración con dj-database-url (más limpio y estándar)
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    # Configuración para PostgreSQL (Neon) usando dj-database-url
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,  # Reutilizar conexiones por 10 minutos
            conn_health_checks=True,  # Verificar salud de conexiones
        )
    }
else:
    # Fallback a SQLite para desarrollo local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'  # Español de Colombia

TIME_ZONE = 'America/Bogota'  # Zona horaria de Colombia

USE_I18N = True

USE_TZ = True

# Configuración de localización
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = 'accounts:login'
# LOGIN_REDIRECT_URL manejado por CustomLoginView según tipo de usuario
LOGOUT_REDIRECT_URL = 'accounts:login'

# Email configuration - Gmail SMTP con clave de aplicación
# IMPORTANTE: Para generar clave de aplicación de Gmail:
# 1. Ir a https://myaccount.google.com/security
# 2. Habilitar verificación en 2 pasos
# 3. Crear clave de aplicación para "S_CONTABLE Django"
# 4. Usar esa clave de 16 caracteres en GOOGLE_APP_PASSWORD
# NUNCA subir la clave de aplicación al repositorio

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')  # Tu email de Gmail
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # Clave de aplicación
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER', '')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# ===== CONFIGURACIÓN DE CONVIVENCIA: SESIONES + JWT =====

# Django REST Framework - SOLO para rutas /api/
# Las vistas MVT (HTML) siguen usando sesiones normalmente
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # JWT SOLO para API (/api/*) - No afecta vistas MVT
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # Sesiones para compatibilidad con browsable API
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # Solo en desarrollo
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Simple JWT Configuration
# Access token: 15 minutos (seguridad)
# Refresh token: 1 día (usabilidad)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,  # Rota refresh tokens por seguridad
    'BLACKLIST_AFTER_ROTATION': True,  # Invalida tokens antiguos
    'UPDATE_LAST_LOGIN': True,  # Actualiza last_login en cada token
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=15),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# CORS Configuration - Para desarrollo local
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React/Vue frontend
    "http://127.0.0.1:3000",
    "http://localhost:8080",  # Vue CLI default
    "http://127.0.0.1:8080",
]

CORS_ALLOW_CREDENTIALS = True  # Para cookies de sesión si es necesario

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = os.getenv(
    'CSRF_TRUSTED_ORIGINS', 
    'http://127.0.0.1:8000,http://localhost:8000,http://127.0.0.1:57765'
).split(',')

# Configuraciones adicionales de CSRF para desarrollo
if DEBUG:
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_HTTPONLY = False
    CSRF_USE_SESSIONS = False
    CSRF_COOKIE_SAMESITE = 'Lax'
    
    # Agregar dominios de desarrollo
    CSRF_TRUSTED_ORIGINS.extend([
        'http://127.0.0.1:57765',  # Browser preview
        'http://localhost:57765',
    ])

# Configuración de sesiones
SESSION_COOKIE_AGE = 3600  # 1 hora
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

# ===== CONFIGURACIÓN DE SEGURIDAD PARA PRODUCCIÓN =====
# Para configuración de producción, consultar documentación de Django Security
