# Generated by Django 5.2.7 on 2025-10-21 19:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('contabilidad', '0001_initial'),
        ('empresas', '0001_initial'),
        ('facturacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno de la cuenta', max_length=10, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Cuenta')),
                ('tipo_cuenta', models.CharField(choices=[('ahorros', 'Cuenta de Ahorros'), ('corriente', 'Cuenta Corriente'), ('caja', 'Caja General')], max_length=15, verbose_name='Tipo de Cuenta')),
                ('numero_cuenta', models.CharField(blank=True, help_text='Número de cuenta bancaria (si aplica)', max_length=30, verbose_name='Número de Cuenta')),
                ('banco', models.CharField(blank=True, help_text='Nombre del banco (si aplica)', max_length=100, verbose_name='Banco')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo Actual')),
                ('activa', models.BooleanField(default=True, verbose_name='Cuenta Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cuenta_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentacontable', verbose_name='Cuenta Contable Asociada')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pago', models.CharField(help_text='Número consecutivo del pago', max_length=20, verbose_name='Número de Pago')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('tipo_pago', models.CharField(choices=[('cobro', 'Cobro a Cliente'), ('egreso', 'Egreso a Proveedor')], max_length=10, verbose_name='Tipo de Pago')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor del Pago')),
                ('referencia', models.CharField(blank=True, help_text='Número de cheque, referencia de transferencia, etc.', max_length=100, verbose_name='Referencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('anulado', 'Anulado')], default='borrador', max_length=15, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('asiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.asiento', verbose_name='Asiento Contable')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado Por')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
                ('factura', models.ForeignKey(blank=True, help_text='Factura que se está pagando (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.factura', verbose_name='Factura Relacionada')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.metodopago', verbose_name='Método de Pago')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.tercero', verbose_name='Cliente/Proveedor')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-numero_pago'],
                'unique_together': {('empresa', 'numero_pago')},
            },
        ),
    ]
