# Generated by Django 5.2.7 on 2025-11-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('pagado', 'Pagado')], default='pendiente', max_length=15, verbose_name='Estado'),
        ),
    ]
