# Generated by Django 5.2.7 on 2025-11-10 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0003_pagodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagodetalle',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
    ]
