# Generated by Django 5.2.7 on 2025-11-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0004_cambiar_cantidad_a_entero'),
        ('tesoreria', '0004_extractobancario'),
    ]

    operations = [
    ]
