# Generated by Django 5.2.7 on 2025-11-12 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0005_merge_20251111_0804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extractobancario',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Extracto Bancario', 'verbose_name_plural': 'Extractos Bancarios'},
        ),
        migrations.AddField(
            model_name='pago',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, help_text='Cuenta bancaria desde/hacia la que se realiza el pago', null=True, on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cuentabancaria', verbose_name='Cuenta Bancaria'),
        ),
    ]
