# Generated by Django 5.2.7 on 2025-11-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=15, verbose_name='Estado'),
        ),
    ]
