# Generated by Django 5.2.7 on 2025-10-21 19:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.CharField(help_text='Número consecutivo del asiento', max_length=20, verbose_name='Número de Asiento')),
                ('fecha_asiento', models.DateField(verbose_name='Fecha del Asiento')),
                ('tipo_asiento', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], default='manual', max_length=15, verbose_name='Tipo de Asiento')),
                ('concepto', models.CharField(help_text='Descripción del asiento contable', max_length=300, verbose_name='Concepto')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('total_debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Débito')),
                ('total_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Crédito')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('anulado', 'Anulado')], default='borrador', max_length=15, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('documento_origen', models.CharField(blank=True, help_text='Referencia al documento que generó el asiento', max_length=100, verbose_name='Documento Origen')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado Por')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'ordering': ['-fecha_asiento', '-numero_asiento'],
                'unique_together': {('empresa', 'numero_asiento')},
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código numérico de la cuenta (ej: 1105, 110505)', max_length=20, validators=[django.core.validators.RegexValidator(message='El código debe contener solo números', regex='^[0-9]{1,20}$')], verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Cuenta')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('naturaleza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], help_text='Naturaleza normal de la cuenta (Débito o Crédito)', max_length=1, verbose_name='Naturaleza')),
                ('tipo_cuenta', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('COSTO', 'Costo')], max_length=15, verbose_name='Tipo de Cuenta')),
                ('nivel', models.PositiveIntegerField(default=1, help_text='Nivel jerárquico de la cuenta (1=Mayor, 2=Submyor, etc.)', verbose_name='Nivel')),
                ('acepta_movimiento', models.BooleanField(default=True, help_text='Si la cuenta puede tener partidas contables', verbose_name='Acepta Movimiento')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo Inicial')),
                ('saldo_debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo Débito')),
                ('saldo_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo Crédito')),
                ('activa', models.BooleanField(default=True, verbose_name='Cuenta Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcuentas', to='contabilidad.cuentacontable', verbose_name='Cuenta Padre')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Descripción específica de la partida', max_length=300, verbose_name='Concepto')),
                ('valor_debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Débito')),
                ('valor_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Crédito')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='contabilidad.asiento', verbose_name='Asiento')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentacontable', verbose_name='Cuenta Contable')),
                ('tercero', models.ForeignKey(blank=True, help_text='Tercero relacionado con la partida (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.tercero', verbose_name='Tercero')),
            ],
            options={
                'verbose_name': 'Partida Contable',
                'verbose_name_plural': 'Partidas Contables',
                'ordering': ['asiento', 'orden'],
            },
        ),
    ]
