# Generated by Django 5.2.7 on 2025-11-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='tipo_asiento',
            field=models.CharField(choices=[('ordinario', 'Ordinario'), ('apertura', 'Apertura'), ('ajuste', 'Ajuste'), ('cierre', 'Cierre')], default='ordinario', max_length=15, verbose_name='Tipo de Asiento'),
        ),
    ]
