# Generated by Django 5.2.7 on 2025-10-21 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('diario', 'Libro Diario'), ('mayor', 'Libro Mayor'), ('balance_comprobacion', 'Balance de Comprobación'), ('estado_resultados', 'Estado de Resultados (PyG)'), ('balance_general', 'Balance General'), ('flujo_efectivo', 'Flujo de Efectivo')], max_length=25, verbose_name='Tipo de Reporte')),
                ('nombre_reporte', models.CharField(max_length=200, verbose_name='Nombre del Reporte')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('parametros_adicionales', models.JSONField(blank=True, default=dict, help_text='Parámetros específicos del reporte en formato JSON', verbose_name='Parámetros Adicionales')),
                ('formato_generado', models.CharField(choices=[('html', 'HTML'), ('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel')], max_length=10, verbose_name='Formato Generado')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('numero_registros', models.PositiveIntegerField(default=0, help_text='Cantidad de registros incluidos en el reporte', verbose_name='Número de Registros')),
                ('tiempo_generacion', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Tiempo de Generación (segundos)')),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='reportes/%Y/%m/', verbose_name='Archivo Generado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Generado Por')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Configuración')),
                ('tipo_reporte', models.CharField(choices=[('diario', 'Libro Diario'), ('mayor', 'Libro Mayor'), ('balance_comprobacion', 'Balance de Comprobación'), ('estado_resultados', 'Estado de Resultados (PyG)'), ('balance_general', 'Balance General'), ('flujo_efectivo', 'Flujo de Efectivo')], max_length=25, verbose_name='Tipo de Reporte')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('configuracion', models.JSONField(default=dict, help_text='Configuración del reporte en formato JSON', verbose_name='Configuración')),
                ('es_publica', models.BooleanField(default=False, help_text='Si otros usuarios de la empresa pueden usar esta configuración', verbose_name='Es Pública')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('veces_utilizada', models.PositiveIntegerField(default=0, verbose_name='Veces Utilizada')),
                ('ultima_utilizacion', models.DateTimeField(blank=True, null=True, verbose_name='Última Utilización')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
                'ordering': ['tipo_reporte', 'nombre'],
                'unique_together': {('empresa', 'nombre', 'creado_por')},
            },
        ),
    ]
