# Generated by Django 5.2.7 on 2025-10-21 19:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(help_text='Número de Identificación Tributaria con dígito de verificación', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Formato NIT: 123456789-0', regex='^\\d{9,11}-\\d{1}$')], verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('tipo_empresa', models.CharField(choices=[('SAS', 'Sociedad por Acciones Simplificada'), ('LTDA', 'Sociedad Limitada'), ('SA', 'Sociedad Anónima'), ('ESAL', 'Entidad Sin Ánimo de Lucro'), ('PERSONA_NATURAL', 'Persona Natural'), ('OTRO', 'Otro')], default='SAS', max_length=20, verbose_name='Tipo de Empresa')),
                ('regimen_tributario', models.CharField(choices=[('COMUN', 'Régimen Común'), ('SIMPLIFICADO', 'Régimen Simplificado'), ('ESPECIAL', 'Régimen Especial')], default='COMUN', max_length=15, verbose_name='Régimen Tributario')),
                ('responsable_iva', models.BooleanField(default=True, verbose_name='Responsable de IVA')),
                ('gran_contribuyente', models.BooleanField(default=False, verbose_name='Gran Contribuyente')),
                ('autorretenedor', models.BooleanField(default=False, verbose_name='Autorretenedor')),
                ('direccion', models.TextField(max_length=300, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(default='Cundinamarca', max_length=100, verbose_name='Departamento')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato: +5713001234567 o 13001234567', regex='^\\+?57?[0-9]{7,12}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Corporativo')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('moneda_base', models.CharField(default='COP', help_text='Código ISO de la moneda (COP, USD, EUR)', max_length=3, verbose_name='Moneda Base')),
                ('periodo_contable', models.CharField(choices=[('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='ANUAL', max_length=10, verbose_name='Período Contable')),
                ('activa', models.BooleanField(default=True, verbose_name='Empresa Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_propias', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seleccion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Selección')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa Activa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_activa_sesion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Empresa Activa por Usuario',
                'verbose_name_plural': 'Empresas Activas por Usuario',
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('contador', 'Contador'), ('operador', 'Operador')], max_length=10, verbose_name='Rol en la Empresa')),
                ('activo', models.BooleanField(default=True, verbose_name='Perfil Activo')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfiles_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado Por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario en Empresa',
                'verbose_name_plural': 'Perfiles de Usuarios en Empresas',
                'ordering': ['empresa__razon_social', 'usuario__username'],
                'unique_together': {('usuario', 'empresa')},
            },
        ),
    ]
