# Generated by Django 5.2.7 on 2025-10-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_perfilempresa_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilempresa',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('contador', 'Contador'), ('operador', 'Operador'), ('observador', 'Observador')], max_length=10, verbose_name='Rol en la Empresa'),
        ),
    ]
