# Generated by Django 5.2.7 on 2025-10-24 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_perfilempresa_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('empresa_crear', 'Empresa creada'), ('empresa_editar', 'Empresa editada'), ('empresa_activar', 'Empresa activada'), ('empresa_desactivar', 'Empresa desactivada'), ('usuario_login', 'Inicio de sesión'), ('usuario_logout', 'Cierre de sesión'), ('usuario_cambio_empresa', 'Cambio de empresa activa'), ('usuario_perfil_actualizado', 'Perfil actualizado'), ('tercero_crear', 'Tercero creado'), ('tercero_editar', 'Tercero editado'), ('tercero_eliminar', 'Tercero eliminado'), ('producto_crear', 'Producto creado'), ('producto_editar', 'Producto editado'), ('producto_eliminar', 'Producto eliminado'), ('factura_crear', 'Factura creada'), ('factura_editar', 'Factura editada'), ('factura_anular', 'Factura anulada'), ('factura_pagar', 'Factura pagada'), ('pago_crear', 'Pago registrado'), ('pago_editar', 'Pago editado'), ('pago_anular', 'Pago anulado'), ('cobro_crear', 'Cobro registrado'), ('cobro_editar', 'Cobro editado'), ('asiento_crear', 'Asiento contable creado'), ('asiento_editar', 'Asiento contable editado'), ('asiento_eliminar', 'Asiento contable eliminado'), ('reporte_generar', 'Reporte generado'), ('reporte_exportar', 'Reporte exportado'), ('configuracion_cambiar', 'Configuración modificada'), ('error_sistema', 'Error del sistema'), ('acceso_denegado', 'Acceso denegado')], max_length=50, verbose_name='Tipo de Acción')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción realizada', verbose_name='Descripción')),
                ('modelo_afectado', models.CharField(blank=True, help_text='Nombre del modelo que fue modificado', max_length=100, null=True, verbose_name='Modelo Afectado')),
                ('objeto_id', models.PositiveIntegerField(blank=True, help_text='ID del objeto que fue modificado', null=True, verbose_name='ID del Objeto')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado anterior del objeto (JSON)', null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado nuevo del objeto (JSON)', null=True, verbose_name='Datos Nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/dispositivo', null=True, verbose_name='User Agent')),
                ('url_solicitada', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Solicitada')),
                ('metodo_http', models.CharField(blank=True, help_text='GET, POST, PUT, DELETE, etc.', max_length=10, null=True, verbose_name='Método HTTP')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('duracion_ms', models.PositiveIntegerField(blank=True, help_text='Tiempo que tomó procesar la acción', null=True, verbose_name='Duración (ms)')),
                ('exitosa', models.BooleanField(default=True, help_text='Si la acción se completó exitosamente', verbose_name='Exitosa')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si la acción falló', null=True, verbose_name='Mensaje de Error')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa en la que se realizó la acción', null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Cambio',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', '-fecha_hora'], name='empresas_hi_usuario_87ef64_idx'), models.Index(fields=['empresa', '-fecha_hora'], name='empresas_hi_empresa_99503a_idx'), models.Index(fields=['tipo_accion', '-fecha_hora'], name='empresas_hi_tipo_ac_901882_idx'), models.Index(fields=['-fecha_hora'], name='empresas_hi_fecha_h_030b26_idx')],
            },
        ),
    ]
